grafana:
  image:
    repository: grafana/grafana
    tag: latest
  service:
    type: NodePort
    port: 3000
    nodePort: 30001
  adminPassword: admin  # Default password

postgresql:
  image:
    repository: postgres
    tag: 13
  service:
    port: 5432
  password: grafanapass
  database: grafanadb
