apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-scan-grafana
spec:
  template:
    spec:
      containers:
      - name: trivy
        image: aquasec/trivy:latest
        command:
        - trivy
        args:
        - image
        - --severity
        - HIGH,CRITICAL
        - --format
        - table
        - cgr.dev/chainguard/grafana:latest
      restartPolicy: Never
