apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-scan-redash
spec:
  template:
    spec:
      containers:
      - name: trivy
        image: aquasec/trivy:latest
        command:
        - trivy
        args:
        - image
        - --severity
        - HIGH,CRITICAL
        - --format
        - table
        - redash/redash:10.1.0
      restartPolicy: Never
