apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aqua
  namespace: trivy-system
spec:
  interval: 1h
  url: https://aquasecurity.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 1h
  chart:
    spec:
      chart: trivy-operator
      version: "0.16.1"
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: trivy-system
  values:
    trivy:
      ignoreUnfixed: true
    operator:
      scanJobTTL: 24h
      vulnerabilityScannerEnabled: true
      configAuditScannerEnabled: true
      rbacAssessmentEnabled: true
