apiVersion: batch/v1
kind: Job
metadata:
  name: init-sample-data
spec:
  template:
    spec:
      containers:
      - name: init-sample-data
        image: postgres:13
        command:
        - /bin/bash
        - -c
        - |
          psql "postgresql://postgres:grafanapass@grafana-dashboard-postgresql:5432/grafanadb" <<'EOSQL'
          -- Create time-series metrics table
          CREATE TABLE server_metrics (
              time_stamp TIMESTAMP NOT NULL,
              server_id VARCHAR(50),
              cpu_usage DECIMAL(5,2),
              memory_usage DECIMAL(5,2),
              disk_usage DECIMAL(5,2),
              network_in DECIMAL(10,2),
              network_out DECIMAL(10,2)
          );

          -- Create sample server metrics data
          INSERT INTO server_metrics (time_stamp, server_id, cpu_usage, memory_usage, disk_usage, network_in, network_out)
          SELECT
              NOW() - (INTERVAL '1 hour' * generate_series(1, 24*7)),  -- Last 7 days of data
              'server-' || (random() * 3 + 1)::int,  -- 3 servers
              35 + (random() * 60)::decimal(5,2),    -- CPU usage between 35-95%
              40 + (random() * 50)::decimal(5,2),    -- Memory usage between 40-90%
              30 + (random() * 60)::decimal(5,2),    -- Disk usage between 30-90%
              (random() * 1000)::decimal(10,2),      -- Network in (MB/s)
              (random() * 1000)::decimal(10,2)       -- Network out (MB/s)
          FROM generate_series(1, 24*7);

          -- Create application metrics table
          CREATE TABLE application_metrics (
              time_stamp TIMESTAMP NOT NULL,
              app_name VARCHAR(50),
              response_time DECIMAL(10,2),
              error_rate DECIMAL(5,2),
              requests_per_second INTEGER
          );

          -- Insert sample application metrics
          INSERT INTO application_metrics (time_stamp, app_name, response_time, error_rate, requests_per_second)
          SELECT
              NOW() - (INTERVAL '1 hour' * generate_series(1, 24*7)),
              'app-' || (random() * 2 + 1)::int,     -- 2 applications
              50 + (random() * 200)::decimal(10,2),  -- Response time between 50-250ms
              0 + (random() * 5)::decimal(5,2),      -- Error rate between 0-5%
              10 + (random() * 90)::int              -- 10-100 requests per second
          FROM generate_series(1, 24*7);
          EOSQL
      restartPolicy: Never
