apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: 5000
    nodePort: {{ .Values.server.service.nodePort }}
  selector:
    app: redash
    role: server
