name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # The first call to the action will invoke setup-trivy and install trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: .
          format: 'table'
          exit-code: 0 # 1 will fail build on high, criticals
          severity: 'CRITICAL, HIGH'

      - name: Scan Container Images
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          image-ref: 'redash/redash:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          skip-setup-trivy: true

      - name: Upload Trivy container results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'my-analysis-tool'
