name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # The first call to the action will invoke setup-trivy and install trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: .
          format: 'sarif'
          exit-code: 0 # 1 will fail build on high, criticals
          # severity: HIGH, CRITICAL
          output: 'trivy-results-vuln.sarif'

      - name: Upload Trivy vuln results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-vuln.sarif'

      - name: Scan Container Images
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'redash/redash:latest'
          format: 'sarif'
          output: 'trivy-results-container.sarif'
          skip-setup-trivy: true

      - name: Upload Trivy container results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-container.sarif'
